-- Additive security metadata for contact enquiries. Existing rows are retained
-- and default to "legitimate" because there is not enough evidence to relabel them.
ALTER TABLE public.contact_enquiries
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'legitimate',
  ADD COLUMN IF NOT EXISTS spam_reasons text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS request_id uuid,
  ADD COLUMN IF NOT EXISTS source_ip_hash text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'contact_enquiries_status_check'
  ) THEN
    ALTER TABLE public.contact_enquiries
      ADD CONSTRAINT contact_enquiries_status_check
      CHECK (status IN ('legitimate', 'suspected_spam', 'blocked'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS contact_enquiries_status_created_at_idx
  ON public.contact_enquiries (status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.contact_submission_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL,
  ip_hash text NOT NULL,
  payload_hash text NOT NULL,
  outcome text NOT NULL CHECK (outcome IN ('accepted', 'duplicate', 'rate_limited')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contact_submission_attempts_ip_created_idx
  ON public.contact_submission_attempts (ip_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS contact_submission_attempts_payload_created_idx
  ON public.contact_submission_attempts (payload_hash, created_at DESC);

ALTER TABLE public.contact_submission_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.contact_submission_attempts FROM anon, authenticated;

-- Serialize checks per anonymized source so concurrent requests cannot race the
-- count/duplicate checks. Five accepted submissions per 15 minutes are allowed;
-- identical content is rejected for 10 minutes.
CREATE OR REPLACE FUNCTION public.check_contact_submission(
  p_ip_hash text,
  p_payload_hash text,
  p_request_id uuid
)
RETURNS TABLE (allowed boolean, reason text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  accepted_count integer;
BEGIN
  IF p_ip_hash IS NULL OR length(p_ip_hash) <> 64
     OR p_payload_hash IS NULL OR length(p_payload_hash) <> 64
     OR p_request_id IS NULL THEN
    RETURN QUERY SELECT false, 'invalid'::text;
    RETURN;
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(p_ip_hash, 0));

  IF EXISTS (
    SELECT 1
      FROM public.contact_submission_attempts
     WHERE payload_hash = p_payload_hash
       AND outcome = 'accepted'
       AND created_at > now() - interval '10 minutes'
  ) THEN
    INSERT INTO public.contact_submission_attempts
      (request_id, ip_hash, payload_hash, outcome)
    VALUES (p_request_id, p_ip_hash, p_payload_hash, 'duplicate');
    RETURN QUERY SELECT false, 'duplicate'::text;
    RETURN;
  END IF;

  SELECT count(*)::integer
    INTO accepted_count
    FROM public.contact_submission_attempts
   WHERE ip_hash = p_ip_hash
     AND outcome = 'accepted'
     AND created_at > now() - interval '15 minutes';

  IF accepted_count >= 5 THEN
    INSERT INTO public.contact_submission_attempts
      (request_id, ip_hash, payload_hash, outcome)
    VALUES (p_request_id, p_ip_hash, p_payload_hash, 'rate_limited');
    RETURN QUERY SELECT false, 'rate_limit'::text;
    RETURN;
  END IF;

  INSERT INTO public.contact_submission_attempts
    (request_id, ip_hash, payload_hash, outcome)
  VALUES (p_request_id, p_ip_hash, p_payload_hash, 'accepted');
  RETURN QUERY SELECT true, 'allowed'::text;
END;
$$;

REVOKE ALL ON FUNCTION public.check_contact_submission(text, text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_contact_submission(text, text, uuid) TO service_role;

CREATE TABLE IF NOT EXISTS public.admin_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL,
  ip_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_login_attempts_ip_created_idx
  ON public.admin_login_attempts (ip_hash, created_at DESC);
ALTER TABLE public.admin_login_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.admin_login_attempts FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.check_admin_login_attempt(
  p_ip_hash text,
  p_request_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  attempt_count integer;
BEGIN
  IF p_ip_hash IS NULL OR length(p_ip_hash) <> 64 OR p_request_id IS NULL THEN
    RETURN false;
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('admin:' || p_ip_hash, 0));
  SELECT count(*)::integer INTO attempt_count
    FROM public.admin_login_attempts
   WHERE ip_hash = p_ip_hash
     AND created_at > now() - interval '15 minutes';
  IF attempt_count >= 5 THEN
    RETURN false;
  END IF;
  INSERT INTO public.admin_login_attempts (request_id, ip_hash)
  VALUES (p_request_id, p_ip_hash);
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.check_admin_login_attempt(text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_admin_login_attempt(text, uuid) TO service_role;

-- Keep the abuse-control table bounded without retaining long-term source data.
-- Schedule this statement daily using Supabase Cron/pg_cron if available:
-- DELETE FROM public.contact_submission_attempts WHERE created_at < now() - interval '7 days';
-- DELETE FROM public.admin_login_attempts WHERE created_at < now() - interval '7 days';
